[deps]
JuliaLowering = "f3c80556-a63f-4383-b822-37d64f81a311"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"

[sources]
JuliaLowering = {path = "JuliaLowering"}
JuliaSyntax = {path = "JuliaSyntax"}
